export const gameinfo = {
  1: {
    "name": "Beginner DnD",
    "price": 20,
    "day": "Monday",
    "time": "9pm",
    "difficulty": "Easy",
    "info": "Welcome to DnD! This game is suitable for first-time players or those wanting to brush up their dragon slaying skills.",
    "host": "Alex",
    "hostid": 123,
    "datetime": "",
    "gametype": "DnD",
    "logo": '/game_logos/dnd.png',
    "location": "Discord",
    "gameID": 1,
    "tags": ["Dungeons & Dragons", "beginner", "fun"],
    "gallery": ["/game_logos/dnd1.jpeg", "/game_logos/dnd2.jpg"],
  },
  2: {
    "name": "The Great Mage",
    "price": 10,
    "day": "Thursday",
    "time": "6pm",
    "difficulty": "Medium",
    "info": "Welcome to Magic! This game is suitable for intermediate players. We allow all decks/expansions and will focus learning on how to best utilize mage cards. \n Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "host": "Brian",
    "hostid": 111,
    "datetime": "",
    "gametype": "Magic",
    "logo": '/game_logos/mtg1.jpg',
    "location": "Zoom",
    "gameID": 2,
    "tags": ["Magic: the Gathering", "intermediate", "fantasy"],
    "gallery": ["/game_logos/magic1.jpeg", "/game_logos/magic2.jpg"],
  },
  3: {
    "name": "Advanced Magic: Elemental Strike",
    "price": 25,
    "day": "Saturday",
    "time": "2pm",
    "difficulty": "Medium",
    "info": "Look no further if you're a pro at Magic and looking for a challenge! This game is catered for advanced players. We allow all decks/expansions and guarantee a thrilling game. \n Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "host": "Tanvir",
    "hostid": 420,
    "datetime": "",
    "gametype": "Magic",
    "logo": '/game_logos/mtg2.jpg',
    "location": "Skype",
    "gameID": 3,
    "tags": ["Magic: the Gathering", "advanced", "intense"],
    "gallery": ["/game_logos/magic3.jpg", "/game_logos/magic2.jpg"],

  },
  4: {
    "name": "Pandemic",
    "price": 25,
    "day": "Tuesday",
    "time": "2pm",
    "difficulty": "Easy",
    "info": "This game is suitable for casual and new players - a perfect introduction to Pandemic! \n Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    "host": "Tanvir",
    "hostid": 420,
    "datetime": "",
    "gametype": "Pandemic",
    "logo": '/game_logos/pandemic.jpg',
    "location": "Zoom",
    "gameID": 4,
    "tags": ["Pandemic", "beginner"],
    "gallery": ["/game_logos/pandemic2.jpg", "/game_logos/pandemic3.jpg"],
  },
  5: {
    "name": "Pandemic - Remastered",
    "price": 25,
    "day": "Tuesday",
    "time": "2pm",
    "difficulty": "Insane",
    "info": "This game is suitable for experienced players. \n Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    "host": "Alex",
    "hostid": 123,
    "datetime": "",
    "gametype": "Pandemic",
    "logo": '/game_logos/pandemic1.jpg',
    "location": "Skype",
    "gameID": 5,
    "tags": ["Pandemic", "advanced"],
    "gallery": ["/game_logos/pandemic2.jpg", "/game_logos/pandemic3.jpg"],
  },
  6: {
    "name": "CIT: Living Nightmare",
    "price": 50,
    "day": "Any",
    "time": "9pm",
    "difficulty": "Easy",
    "info": `Turns out that weird smell in the sunlab wasn't just from dirty keyboards... this campaign is guaranteed to make you suffer and scarred for life. You'll have to unwillingly venture into the CIT -- can you get out? \n This game is designed for newer players to Dungeons and Dragons. I am willing to cater to characters that you may have already. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.`,
    "host": "Tanvir",
    "hostid": 420,
    "datetime": "",
    "gametype": "DnD",
    "logo": '/game_logos/cit.jpeg',
    "location": "Discord",
    "gameID": 6,
    "tags": ["Dungeons & Dragons", "hard"],
    "gallery": ["/game_logos/cit2.jpg", "/game_logos/sunlab.jpg"],
  },
  7: {
    "name": "Transported to Another World",
    "price": 30,
    "day": "Friday",
    "time": "12pm",
    "difficulty": "Hard",
    "info": "The sun was shining brightly. It was a normal Friday and you were on the way to work. Suddenly, a truck... ? Here begins your life in a new world! \n I have worlds ready but if you have any particular preference feel free to let me know and I will consider it. Character requests are not accepted - the character you are assigned is completely random, which is part of the fun!",
    "host": "Truckkun",
    "hostid": 1000,
    "gametype": "DnD",
    "logo": '/game_logos/truck.png',
    "location": "Discord",
    "gameID": 7,
    "tags": ["Dungeons & Dragons", "hard", "realistic"],
    "gallery": ["/game_logos/aincrad.jpg", "/game_logos/overlord.jpg"],
  },
  8: {
    "name": "Cyberpunk 2077",
    "price": 60,
    "day": "Wednesday",
    "time": "3pm",
    "difficulty": "Medium",
    "info": "Cyberpunk 2077 is an open-world, action-adventure story set in Night City, a megalopolis obsessed with power, glamour and body modification. You can customize your character’s cyberware, skillset and playstyle, and explore a vast city where the choices you make shape the story and the world around you.",
    "host": "Johnny Silverhand",
    "hostid": 2077,
    "gametype": "Cyberpunk",
    "logo": '/game_logos/cyberpunk.jpg',
    "location": "Zoom",
    "gameID": 8,
    "tags": ["Cyberpunk", "medium"],
    "gallery": ["/game_logos/cp1.jpg", "/game_logos/cp2.jpeg"],
  }
}

export const hostData = {
  1000: {
    "name": "Truckkun",
    "rating": 5.0,
    "numrating": 8751,
    "intro": "Hey folks, I host many games. My specialty is transporting you out of this world for each one.",
    "reviews": [1, 2, 6],
    "about": "Hello, you may or may not know me. I love getting people into playing games and I guarantee an unforgettable experience. \n Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "numberOfGames": "9829",
    "gamesHosted": ["Dungeons & Dragons",],
    "style": "All of my games are extremely realistic.",
    "hostid": 1000,
    "minPrice": 30,
    "pfp": "./pfp/popcorn.png"
  },
  123: {
    "name": "Alex",
    "rating": 5.0,
    "numrating": 1,
    "intro": "Hello! I'm Alex and I host DnD games. Looking forward to seeing you ingame!",
    "reviews": [1, 2, 3],
    "about": "Hey! I'm Alex. I first got into tabletop games back in the 90's, and now I try to share this experience with others on this platform. \n Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "numberOfGames": 56,
    "gamesHosted": ["Dungeons & Dragons"],
    "style": "I try to add some humor to all my game sessions to help break the ice so if you are into corny jokes, please join my session!",
    "hostid": 123,
    "minPrice": 20,
    "pfp": "./pfp/snootu.png"
  },
  111: {
    "name": "Brian Longggggname",
    "rating": 2.0,
    "numrating": 2,
    "intro": "I'm Brian, and I host DnD and Magic games. Join me for a jolly good time!",
    "reviews": [1, 4, 5],
    "about": "I'm Brian, and I come from the small town of Columbus, Ohio where I grew up playing tabletop games everyday. Now, I try to host games online to get more people into this field! \n Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",
    "numberOfGames": 5,
    "gamesHosted": ["Magic: The Gathering"],
    "style": "I personally try to make each of my games unique by adding in special traits to the games, such as adding in a hidden character.",
    "hostid": 111,
    "minPrice": 10,
    "pfp": "./pfp/snoo.png"
  },
  420: {
    "name": "Tanvir",
    "rating": 5.0,
    "numrating": 1000,
    "intro": "Magic and DnD are the games I host, and I'd love to meet you all ingame for a great time!",
    "reviews": [4, 5, 2],
    "about": "I'm Tanvir and I only recently got into tabletop games during the Corona pandemic. It's a great way to spend time with friends and family, and that's why I host games online to share the joy!",
    "numberOfGames": 23,
    "gamesHosted": ["Magic: The Gathering", "Pandemic"],
    "style": "For my games, I try to make sure to adjust the gameplay to suit the players, so I'm very receptive to feedback. By the end of the session, you may honestly not recognize the game we are playing compared to when we started!",
    "hostid": 420,
    "minPrice": 25,
    "pfp": "./pfp/munchlax.png"
  },
  2077: {
    "name": "Johnny Silverhand",
    "rating": 1.0,
    "numrating": 1,
    "intro": "I'm a professional Cyberpunk host.",
    "reviews": [3, 7],
    "about": "I'm Johnny and I've hosted Cyberpunk 2077 for 15 years so far. If you join one of my games you're sure to have a good time.",
    "numberOfGames": 10,
    "gamesHosted": ["Cyberpunk"],
    "style": "I try to make my games follow the rulebook as close as possible.",
    "hostid": 2077,
    "minPrice": 60,
    "pfp": "./pfp/johnny.jpg"
  }
}

export const reviews = {
  1: {
    "name": "Pat",
    "review": "I had a great experience with this host. He was very welcoming to beginners, and taught me really well. Overall great experience."
  },
  2: {
    "name": "Tan",
    "review": "The game was very well setup. Had some minor issues setting up the game initally due to remote setup, but after that small issue, the rest of the session went amazingly well!"
  },
  3: {
    "name": "Nerak",
    "review": "2/10 would not recommend"
  },
  4: {
    "name": "Patrick",
    "review": "Would highly recommend this host to everyone! He was very humorous while hosting the game and made it a great experience for everyone."
  },
  5: {
    "name": "Kevin",
    "review": "Great experience! Really took the time to make us all feel part of the experience, regardless of the remote setting."
  },
  6: {
    "name": "Karen",
    "review": "10/10 would recommend"
  },
  7: {
    "name": "V",
    "review": "Did not have a good experience. The host was too self-centered and was not welcoming."
  }
}
